#!/bin/bash
#Installing Nagios PLugin 2.3.3 in Ubuntu 20.x
sudo apt-get install -y autoconf gcc libc6 libmcrypt-dev make \ libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl \ gettext
cd /tmp
wget --no-check-certificate -O nagios-plugins.tar.gz \ https://github.com/nagios-plugins/nagios-plugins/archive/release-2. \ 3.3.tar.gz
tar zxf nagios-plugins.tar.gz
cd /tmp/nagios-plugins-release-2.3.3/
sudo ./tools/setup
sudo ./configure \
         --prefix=/opt/nagios \
    --sysconfdir=/etc/nagios \
    --localstatedir=/var/nagios \
    --libexecdir=/opt/nagios/plugins
sudo make
sudo make install
# Then goto services, select and object and reschedule for next check